export const CATEGORIES={
    GET_ALL_CATEGORIES : "GET_ALL_CATEGORIES",
    GET_ONE_CATEGORY : "GET_ONE_CATEGORY"
}

export const PRODUCTS={
    GET_ALL_PRODUCTS:"GET_ALL_PRODUCTS",
    GET_ONE_PRODUCT:"GET_ONE_PRODUCT"
}

export const SET_AUTHENTIFICATION = "SET_AUTHENTIFICATION"